apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-app-deployment
  labels:
    app: iris
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris-app
        image: ""
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - protocol: TCP
          containerPort: 8080

---

apiVersion: v1
kind: Service
metadata: 
  name: iris-app-service
spec:
  selector:
    app: iris
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
