apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-app-deployment
  labels:
    app: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - name: iris-app
        image: "gcr.io/sandfox/iris-app:v1"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - protocol: TCP
          containerPort: 5000
